include: '/common/push-image/.gitlab-ci.yml'

.build_app: &build_app
              mkdir -p bin;
              cd cmd/$SUB_MODULE;
              CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X main.Version=$VERSION" -o ../../bin/;
              cd - > /dev/null;

.build_image: &build_image
                docker build --build-arg SUB_MODULE=$SUB_MODULE -t $MODULE_PREFIX-$SUB_MODULE:$VERSION -f $DOCKER_FILE .;

# 修改点：
# 1、没有push镜像
.golang_build_image_base_v2:
  stage: build
  image: 172.1.1.1/common/golang:1.20.3
  tags:
    - x86
  interruptible: true
  variables:
    SUB_MODULE: default
    MODULE_PREFIX: default
    IMAGE_GROUP: default
    DOCKER_FILE: Dockerfile
  script:
    - |
      if [ -z ${CI_COMMIT_TAG} ];then
      VERSION=${CI_COMMIT_SHORT_SHA};
      else
      VERSION=${CI_COMMIT_TAG};
      fi;
    - echo "VERSION:$VERSION"
    - *build_app
    - *build_image
